cookbook_path    "C:\chef\cookbooks"
chef_repo_path   "C:\chef"
data_bag_path    "C:\chef\data_bags"
role_path        "C:\chef\roles"
environment_path "C:\chef\environments"
json_attribs     "C:\chef\chef-solo\node.json"
