source "https://supermarket.chef.io"

##SOURCE : LOCAL COOKBOOKS##
cookbook 'iis', path: 'C:\chef\cookbooks\iis'
cookbook 'windows_updates', 'C:\chef\cookbooks\windows_updates'

##SOURCE : SUPERMARKET##
cookbook 'windows'
cookbook 'windows_firewall', '~> 3.0.2'

